services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    environment:
      - HOST=db

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file: .env
    volumes: 
      - data:/var/lib/postgresql/data

volumes:
  data:
    external: true